[platformio]
default_envs = pn5180

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 115200
lib_deps =
  miguelbalboa/MFRC522 @ ^1.4.12
  adafruit/Adafruit PN532 @ ^1.3.4

[env:rc522]
build_flags = -DRFID_READER=READER_RC522

[env:pn532]
build_flags = -DRFID_READER=READER_PN532

[env:pn5180]
build_flags = -DRFID_READER=READER_PN5180
lib_deps =
  ${env.lib_deps}
  https://github.com/wilson-elechouse/PN5180_ELECHOUSE.git#c413f0a91e8efa317256afb1e3bba074d3f122dc

[env:pn532-ota]
extends = env:pn532
upload_protocol = espota
upload_port = bambu-rfid.local
upload_flags = --auth=bambu-rfid

[env:pn5180-ota]
extends = env:pn5180
upload_protocol = espota
upload_port = bambu-rfid.local
upload_flags = --auth=bambu-rfid
