#pragma once

// Kept in flash; no filesystem upload step is required.
static const char WEB_UI[] PROGMEM = R"HTML(
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Bambu RFID Workbench</title><style>
:root{color-scheme:dark;--bg:#101411;--panel:#19201b;--line:#303a32;--text:#f2f5f2;--muted:#a9b4ac;--green:#51d17b;--red:#ff6b6b;--amber:#f7c55a}*{box-sizing:border-box}body{margin:0;font:15px/1.45 system-ui,sans-serif;background:linear-gradient(135deg,#0b0f0c,#142018);color:var(--text)}main{width:min(1080px,94vw);margin:28px auto 60px}h1{font-size:clamp(26px,5vw,44px);margin:0 0 4px}h2{font-size:19px;margin:0 0 14px}.lead,.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:22px}.card{background:rgba(25,32,27,.94);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 16px 42px #0004}.wide{grid-column:1/-1}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}button,input{font:inherit;border-radius:9px;border:1px solid var(--line);padding:10px 12px}button{cursor:pointer;background:#29342c;color:var(--text)}button.primary{background:var(--green);color:#07140a;border:0;font-weight:700}button.danger{background:#572424;border-color:#8e3d3d}button:disabled{opacity:.4;cursor:not-allowed}input{background:#101511;color:var(--text);min-width:180px;flex:1}input[type=checkbox]{min-width:0;flex:0;accent-color:var(--green)}.toggle{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;color:var(--muted)}.status{padding:10px 12px;border-radius:9px;background:#111713;margin:10px 0;color:var(--muted)}.ok{color:var(--green)}.bad{color:var(--red)}.warn{color:var(--amber)}dl{display:grid;grid-template-columns:140px 1fr;gap:7px 12px;margin:12px 0}dt{color:var(--muted)}dd{margin:0;overflow-wrap:anywhere}.files{max-height:360px;overflow:auto;border:1px solid var(--line);border-radius:10px}.entry{display:flex;width:100%;text-align:left;border:0;border-bottom:1px solid var(--line);border-radius:0;background:#151b17}.entry:hover{background:#222c25}.crumb{margin-bottom:10px;overflow-wrap:anywhere}code{font-size:13px}.notice{border-left:3px solid var(--amber);padding:8px 12px;color:#dfd7c6;background:#2a2417}small{color:var(--muted)}summary{cursor:pointer;font-size:17px;font-weight:700}details[open] summary{margin-bottom:14px}@media(max-width:720px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}dl{grid-template-columns:105px 1fr}}
</style></head><body><main><h1>Bambu RFID Workbench</h1><div class="lead">ESP32 + PN532 · exact signed-tag reader and FUID writer</div>
<div id="top" class="status">Connecting…</div><div class="grid">
<section class="card wide"><h2>1 · Read a tag</h2><p class="muted">Place one tag flat over the PN532 antenna. Auto-scan reads it once and waits for removal before accepting another.</p><button class="primary" onclick="scan()">Scan now</button> <a id="download" hidden><button>Download dump</button></a><label class="toggle"><input id="autoScan" type="checkbox" onchange="setAutoScan(this.checked)"> Auto-scan</label><div id="tag"><p class="muted">No tag read yet.</p></div></section>
<section class="card wide"><h2>2 · Choose an exact signed library dump</h2><div class="notice">Changing material, color, or any signed field invalidates the Bambu signature. This browser selects complete, unmodified community dumps only.</div><p class="crumb"><button onclick="browse('')">Library root</button> <span id="path"></span></p><div id="library" class="files"><div class="status">Open the library after the ESP32 has internet access.</div></div><div id="selected" class="status">No dump loaded.</div></section>
<section class="card wide"><h2>3 · Write a blank FUID tag</h2><div class="notice">Irreversible. Currently limited to an unpersonalized FUID whose factory UID is <code>AA55C396</code>. UFUID sealing is not performed by this PN532 firmware.</div><p>Remove the source tag, place one blank FUID on the reader, type <code>WRITE</code>, then start.</p><div class="row"><input id="confirm" autocomplete="off" placeholder="Type WRITE"><button id="write" class="danger" onclick="writeTag()" disabled>Write exact clone</button></div><div id="job" class="status">Idle</div></section>
<details id="networkSettings" class="card wide"><summary>Network settings</summary><div id="network" class="status"></div><form onsubmit="saveWifi(event)"><div class="row"><input name="ssid" placeholder="Wi-Fi SSID" required><input name="password" type="password" placeholder="Wi-Fi password"><button>Save & restart</button></div></form><p><small>The recovery setup AP remains available at 192.168.4.1.</small></p></details>
<details class="card wide"><summary>Firmware update</summary><div class="notice">Upload only a firmware image built for this ESP32 project. Keep power connected until the device restarts.</div><form onsubmit="uploadFirmware(event)"><div class="row"><input id="firmware" name="firmware" type="file" accept=".bin,application/octet-stream" required><input id="otaPassword" type="password" placeholder="OTA password" required><button class="danger">Install & restart</button></div></form><div id="otaStatus" class="status">No update running.</div></details>
</div></main><script>
const API='https://api.github.com/repos/queengooborg/Bambu-Lab-RFID-Library/contents/';let loaded=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function req(url,opt){const r=await fetch(url,opt);const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={ok:false,message:t}}if(!r.ok)throw Error(j.message||t||r.status);return j}
async function status(){const banner=document.getElementById('top'),net=document.getElementById('network'),settings=document.getElementById('networkSettings'),autoToggle=document.getElementById('autoScan'),jobBox=document.getElementById('job'),writeButton=document.getElementById('write'),tagBox=document.getElementById('tag'),downloadLink=document.getElementById('download'),selectedBox=document.getElementById('selected');try{const s=await req('/api/status');banner.textContent=s.message||'Ready';banner.className='status '+(s.ok?'ok':'warn');net.innerHTML=`Station: <b>${esc(s.station)}</b><br>IP: ${esc(s.ip)}<br>Setup AP: ${esc(s.ap)}`;if(!s.ok)settings.open=true;autoToggle.checked=s.autoScan;autoToggle.disabled=s.busy;jobBox.textContent=s.job;jobBox.className='status '+(s.jobOk?'ok':s.busy?'warn':'');loaded=s.dumpLoaded;writeButton.disabled=!loaded;if(s.tag){tagBox.innerHTML=`<dl><dt>UID</dt><dd>${esc(s.tag.uid)}</dd><dt>Material</dt><dd>${esc(s.tag.detailedType)}</dd><dt>Variant</dt><dd>${esc(s.tag.variant)}</dd><dt>Color</dt><dd><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:${esc(s.tag.color.slice(0,7))}"></span> ${esc(s.tag.color)}</dd><dt>Weight</dt><dd>${esc(s.tag.weight)} g</dd><dt>Diameter</dt><dd>${esc(s.tag.diameter)} mm</dd><dt>Production</dt><dd>${esc(s.tag.production)}</dd></dl>`;downloadLink.hidden=false;downloadLink.href='/api/dump';downloadLink.download=`bambu-${s.tag.uid}.bin`}if(s.dumpLoaded)selectedBox.innerHTML=`Loaded: <b>${esc(s.dumpName)}</b><br>Source UID: <code>${esc(s.dumpUid)}</code>`}catch(e){banner.textContent=e.message;banner.className='status bad';settings.open=true}setTimeout(status,1200)}
async function scan(){await req('/api/scan',{method:'POST'});status()}
async function setAutoScan(enabled){try{await req('/api/autoscan',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'enabled='+(enabled?'1':'0')})}catch(e){alert(e.message)}status()}
async function saveWifi(e){e.preventDefault();const f=new FormData(e.target);await req('/api/wifi',{method:'POST',body:new URLSearchParams(f)});document.getElementById('top').textContent='Saved. Restarting…'}
async function browse(path){const box=document.getElementById('library');box.innerHTML='<div class="status">Loading GitHub library…</div>';document.getElementById('path').textContent=path;try{const u=API+path.split('/').filter(Boolean).map(encodeURIComponent).join('/')+'?ref=main';const r=await fetch(u,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error(`GitHub: ${r.status}`);const a=await r.json();box.innerHTML='';const parent=path.split('/').slice(0,-1).join('/');if(path)addEntry('↩ ..',()=>browse(parent));a.filter(x=>x.type==='dir'||(x.type==='file'&&x.name.endsWith('-dump.bin')&&x.size===1024)).forEach(x=>addEntry((x.type==='dir'?'📁 ':'💾 ')+x.name,()=>x.type==='dir'?browse(x.path):loadDump(x.path)))}catch(e){box.innerHTML=`<div class="status bad">${esc(e.message)}. Check internet access and GitHub rate limits.</div>`}}
function addEntry(label,fn){const b=document.createElement('button');b.className='entry';b.textContent=label;b.onclick=fn;document.getElementById('library').appendChild(b)}
async function loadDump(path){const selectedBox=document.getElementById('selected'),writeButton=document.getElementById('write');selectedBox.textContent='Downloading through ESP32…';try{const j=await req('/api/library/load',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'path='+encodeURIComponent(path)});selectedBox.innerHTML=`Loaded: <b>${esc(j.name)}</b><br>Source UID: <code>${esc(j.uid)}</code>`;loaded=true;writeButton.disabled=false}catch(e){selectedBox.textContent=e.message;selectedBox.className='status bad'}}
async function writeTag(){const confirmation=document.getElementById('confirm');if(confirmation.value!=='WRITE'){alert('Type WRITE exactly.');return}if(!window.confirm('This permanently consumes one FUID tag. Continue?'))return;await req('/api/write',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'confirm=WRITE'});confirmation.value='';status()}
async function uploadFirmware(e){e.preventDefault();const file=document.getElementById('firmware').files[0],password=document.getElementById('otaPassword').value,box=document.getElementById('otaStatus');if(!file||!file.name.endsWith('.bin')){box.textContent='Select firmware.bin.';box.className='status bad';return}if(!window.confirm(`Install ${file.name} (${Math.ceil(file.size/1024)} KiB) and restart the ESP32?`))return;const body=new FormData();body.append('firmware',file,file.name);box.textContent='Uploading and writing flash…';box.className='status warn';try{const j=await req('/api/firmware',{method:'POST',headers:{'X-OTA-Password':password},body});box.textContent=j.message;box.className='status ok'}catch(err){box.textContent=err.message;box.className='status bad'}}
status();browse('');
</script></body></html>
)HTML";
